{% set version = "1.2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-gwasexacthw
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/GWASExactHW_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/GWASExactHW/GWASExactHW_{{ version }}.tar.gz
  sha256: d3137a478338f03de52b75b3eb1b9cce135c82b81ed39fde692b1e0157ddecf7

build:
  number: 3
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('GWASExactHW')"           # [not win]
    - "\"%R%\" -e \"library('GWASExactHW')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=GWASExactHW
  license: GPL-3.0-only
  summary: This package contains a function to do exact Hardy-Weinburg testing (using Fisher's test) for SNP genotypes as typically obtained in a Genome Wide Association Study (GWAS).
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - jenzopr

# Package: GWASExactHW
# Type: Package
# Title: Exact Hardy-Weinburg testing for Genome Wide Association Studies
# Version: 1.01
# Date: 2013-01-04
# Author: Ian Painter, University of Washington
# Maintainer: Ian Painter <ipainter@u.washington.edu>
# Description: This package contains a function to do exact Hardy-Weinburg testing (using Fisher's test) for SNP genotypes as typically obtained in a Genome Wide Association Study (GWAS).
# License: GPL-3
# LazyLoad: yes
# Packaged: 2013-01-04 20:44:17 UTC; ian
# Repository: CRAN
# Date/Publication: 2013-01-05 08:54:06
# NeedsCompilation: yes
