appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: OtskVBjey0kuB8z13C4QbHLP1FQj52gbIitVb57qYVxI9Q2Q6fdk93JPbJXTxeQJHFv3X8mdU2LfTFQy/MSsw76+IKhi7z6LyZtfkIjMLtVMhVwCS1Romir+Ze2Uy+VTzcH0FwdZZP0FbsxnANA1xzeAXAMixYWsa0V6v2741kthEwEVWX+viEaK2I9VZ/lggGOP0sOAfX2pOOOouXWZuCXgFZhH6puOTNanQmb+lhhe3Q0/ymRbg/xcrnjkz4n2uuExVvwJ8YExwx4jP1AXsjinAJ6/XNx/H/xSZO5Qyx4WkGQEQdEmP70Shw1VRepBehXPQexGwzDxPhhl4sYAkN5m/otQNPxwNz1V2IWVbzhXZRoJblZ0zz2ewcE41ajwx5AnnKneA5ef8uySZMk12ddCw+nkLsAc83qu2LvD3E2G2tzuv15maW62q10QcRJWxBK0G35E0G+Mk1bxia2OLy/lmAN2yBJ22+4c/TY7A9yGNUeSTYvYxs0WMJgcMufSuEYc02N0nlcJNnFuCWz4BPjPPzT3euUvuYdZVRBKt6WY5VNPCZ/zazqGOaopmX/UxnBBl93mqeN4nMNGt8ukamR114k9ruMtY45BqwqK9bpwZBe+8oJjRhPnVP5eqyYEia9Rjwo/tgX+RaqWEl7VBIp65LmMblDqWYibJkRHhxg=
conda_forge_output_validation: true
